### ISSUE TITLE
1주차 숙제 [용구, 지연, 지철]

### ISSUE THREAD

**Issue by jife-archive** [NKLCBJoin/study-room#1]
- [x] #2
- [x] #4
- [x] 지철 : RxSwift, 문법 글 작성 (3개)

## 9/19까지 밑에 댓글로 블로그 주소올리기!

**Comment by jife-archive** [comment]
1. https://jife98.tistory.com/36
2. https://jife98.tistory.com/37
3. https://jife98.tistory.com/38

**Comment by reflash407** [comment]
1. https://velog.io/@reflash407/Git-Commit-Convention
2. https://velog.io/@reflash407/CI-CD란

**Comment by Jixeony** [comment]
https://velog.io/@_jixeony/Git-Commit-Convention
